AllCops:
  TargetRubyVersion: 2.5.3
  Exclude:
    - bin/*
  DisplayCopNames: true
Metrics/BlockLength:
  Exclude:
    - spec/**/*
Metrics/ModuleLength:
  Max: 200
Metrics/ClassLength:
  Max: 200
Style/ClassAndModuleChildren:
  Enabled: false
Style/EmptyMethod:
  EnforcedStyle: expanded
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/EmptyLineAfterMagicComment:
  Enabled: false
Documentation:
  Enabled: false
