require: rubocop-rspec
RSpec/ExampleLength:
  Max: 8
RSpec/MessageSpies:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/NestedGroups:
  Max: 5
RSpec/SubjectStub:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.6.1
  Exclude:
    - bin/*
    - nano_rpc.gemspec
  DisplayCopNames: true
Metrics/BlockLength:
  Exclude:
    - spec/**/*
Metrics/ModuleLength:
  Max: 200
Metrics/ClassLength:
  Max: 200
Style/ClassAndModuleChildren:
  Enabled: false
Style/EmptyMethod:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/EmptyLineAfterMagicComment:
  Enabled: false
Documentation:
  Enabled: false
