require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6.3
  Exclude:
    - bin/*
    - vendor/**/*
Metrics/BlockLength:
  Exclude:
    - nano_rpc.gemspec
    - spec/**/*
RSpec/SubjectStub:
  Exclude:
    - spec/lib/nano_rpc/account_spec.rb
    - spec/lib/nano_rpc/helpers/account_helper_spec.rb
    - spec/lib/nano_rpc/helpers/accounts_helper_spec.rb
    - spec/lib/nano_rpc/helpers/node_helper_spec.rb
    - spec/lib/nano_rpc/helpers/wallet_helper_spec.rb
    - spec/lib/nano_rpc/node_spec.rb
