require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6.3
  Exclude:
    - bin/*
    - nano_rpc.gemspec
  DisplayCopNames: true
Documentation:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/EmptyLineAfterMagicComment:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - spec/**/*
Metrics/ClassLength:
  Max: 200
Metrics/ModuleLength:
  Max: 200
RSpec/ExampleLength:
  Max: 8
RSpec/MultipleExpectations:
  Enabled: false
RSpec/NestedGroups:
  Max: 4
RSpec/SubjectStub:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/EmptyMethod:
  Enabled: false


