language: ruby
cache: bundler
notifications:
  email: false
rvm:
  - 2.5.3
  - 2.6.3
  - jruby-head
before_install:
  - gem update bundler
  - gem update --system
script:
  - bundle exec rspec
  - bundle exec rubocop
